name: Flutter Build APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --debug
        
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/BusineesCard.apk

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/BusineesCard.apk"
          tag: "latest"
          name: "En Güncel BusineesCard APK"
          body: "Bu sürüm otomatik olarak güncellenir. Dosya adı: BusineesCard.apk"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
